datafold/data-diff

- README.md
- dev/prepare_db.pql
It seems a bit more reasonable to just import 1M rows for development to not make it take 10min or so to get started, even longer on other databases. 1M is plenty for getting started
> readme: recommend just 1m rows for development

- data_diff/__main__.py
- data_diff/database.py
- data_diff/sql.py
- tests/test_sql.py
When running this with real customers, it'll be very useful to:
* `EXPLAIN` every query in debug-mode to the debug log
* Add an `--interactive` mode that causes you to confirm after every query + explain has been listed, to ensure we don't e.g. run a full-table scan on a massive table
> cli: EXPLAIN queries, add interactive mode

- dev/prepare_db.pql
- pyproject.toml
A step in the right direction for better integration with preql
> Better prepare_db to use latest preql features

- Dockerfile
- dev/Dockerfile.prestosql.340
- dev/presto-conf/standalone/catalog/jmx.properties
- dev/presto-conf/standalone/catalog/memory.properties
- dev/presto-conf/standalone/catalog/postgresql.properties
- dev/presto-conf/standalone/catalog/tpcds.properties
- dev/presto-conf/standalone/catalog/tpch.properties
- dev/presto-conf/standalone/config.properties
- dev/presto-conf/standalone/jvm.config
- dev/presto-conf/standalone/log.properties
- dev/presto-conf/standalone/node.properties
- docker-compose.yml
- poetry.lock
- pyproject.toml
This adds a `docker-compose` setup for PrestoSQL v 340.
You can run this with `docker-compose up presto`.
It's accessible via:
```python
import prestodb
prestodb.dbapi.connect(host="127.0.0.1", user="presto").cursor().execute('SELECT * FROM system.runtime.nodes')
```
> presto: add docker-compose setup

- README.md
- data_diff/database.py
New format: `snowflake://<user>:<pass>@<account>/<database>/<schema>?warehouse=<warehouse>` 
Example: `snowflake://user:pass@account/xdiffdev/test1?warehouse=INTEGRATION`
I think our URI made more sense before, but sometimes backwards-compatibility trumps common sense.
> Update snowflake URIto align with SQLAlchemy

- data_diff/database.py
- data_diff/diff_tables.py
- data_diff/sql.py
- tests/test_diff_tables.py
Initially I meant to make quoting the column names optional, but now I think it should always be done.
Unless I'm wrong?
> Quote columns; Quote snowflake schema; Force ids as ints

- data_diff/database.py
- data_diff/diff_tables.py
- tests/common.py
- tests/test_api.py
- tests/test_database_types.py
- tests/test_diff_tables.py
- tests/test_normalize_fields.py
Tested on all supported DBs.
We still need more thorough tests, to cover all db types, and more edge-case values.
> Adds support for Numeric types with arbitrary precision

- data_diff/database.py
> Refactor Normalize-types into normalize_timestamp() normalize_number()

- README.md
The data comes from https://github.com/datafold/data-diff/pull/67 which I'll clean up significantly, then submit it for review. I will also need to add some instructions on how to use the benchmarking to generate these graphs
> readme: add performance graph

- data_diff/databases/mysql.py
Corrects a small bug for MySQL
> Small fix for issue #102

- data_diff/databases/presto.py
- dev/presto-conf/standalone/catalog/postgresql.properties
- tests/common.py
- tests/test_database_types.py
First set of changes to allow the test suites to be used for benchmarking:
1. _Actually_ use Presto for inserting/etc., before it was just using the backing Postgres table I think, because it wasn't working properly for me (and fix some Presto related bugs)
2. Add `*Faker` classes that are capable of producing an infinite amount of rows for benchmarking
3. Add pagination for the import into the destination table, required when we do millions of rows
4. Fix Presto rounding (I think this is supporting of (1) that it wasn't tested the way we thought?)
5. Add a few more things to make the test and table names nicer
Just trying to split this up so it's easier to review
> tests: fix presto, add faker classes

- pyproject.toml
Setting author to Datafold team alias to make sure all inquiries are routed to designated team members and handled appropriately.
> Set author to Datafold

- data_diff/databases/mysql.py
- tests/test_database_types.py
@erezsh some more goodies for you: A bunch of `int` / `bigint` tests fail.
Run this branch with `poetry run unittest-parallel -j 64 -k int` to reproduce.
Example error:
```
======================================================================
test_types_redshift_int_to_mysql_bigint_50 (tests.test_database_types.TestDiffCrossDatabaseTables)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/root/.cache/pypoetry/virtualenvs/data-diff-yPhKwkIo-py3.10/lib/python3.10/site-packages/parameterized/parameterized.py", line 533, in standalone_func
return func(*(a + p.args), **p.kwargs)
File "/root/data-diff/tests/test_database_types.py", line 443, in test_types
diff = list(differ.diff_tables(self.table, self.table2))
File …
```
> tests: add bigint/int

- .gitignore
- README.md
- data_diff/diff_tables.py
- tests/common.py
- tests/test_database_types.py
Cleanup of resolved merge conflict from https://github.com/datafold/data-diff/pull/67 based on all the changes in master. Trying to split it up into chunks to make it easier to review (and do an extra pass on it all)
The idea is to dual-purpose a subset of the type test-suite for benchmarking, to ensure it doesn't rust. In particular, to follow-up from https://github.com/datafold/data-diff/pull/106, the changes are to:
* In `BENCHMARK=1` mode, we do not want to drop tables, to prevent waiting for millions of rows to be inserted again. Not even across revisions if we're testing the performance change between two revisions
* Create indexes, to have good performance
* Write benchmark results to stdout and JSONL file(s) for graphing/analysis after
* Insert in larger batches for performance …
> benchmark: add suite

- README.md
Closes https://github.com/datafold/data-diff/issues/130
> Update README.md to include authenticator in Snowflake connection string

- README.md
- data_diff/__main__.py
- data_diff/config.py
- data_diff/databases/base.py
- data_diff/databases/connect.py
- data_diff/databases/database_types.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/snowflake.py
- data_diff/diff_tables.py
- poetry.lock
- pyproject.toml
- tests/test_config.py
> Specify data-diff arguments using config files

- .github/workflows/ci.yml
- .gitignore
- README.md
- data_diff/databases/__init__.py
- data_diff/databases/connect.py
- data_diff/databases/trino.py
- data_diff/diff_tables.py
- dev/trino-conf/etc/catalog/jms.properties
- dev/trino-conf/etc/catalog/memory.properties
- dev/trino-conf/etc/catalog/postgresql.properties
- dev/trino-conf/etc/catalog/tpcds.properties
- dev/trino-conf/etc/catalog/tpch.properties
- dev/trino-conf/etc/config.properties
- dev/trino-conf/etc/jvm.config
- dev/trino-conf/etc/node.properties
- docker-compose.yml
- poetry.lock
- pyproject.toml
- tests/common.py
- tests/test_database_types.py
Mainly based on the Presto integration to serve as a starting point for future development.
> Add support for Trino

- tests/common.py
- tests/test_database_types.py
- tests/test_diff_tables.py
Until now "test_database_types" was the only test that goes beyond mysql.
This PR lays the groundwork for running the rest of the tests on various DBs as well, in order to catch more edge cases.
> Initial support for running the tests for multiple databases (replacing TestWithConnection)

- data_diff/__main__.py
- data_diff/utils.py
- tests/test_config.py
> Print configuration during debug, but with passwords redacted

- data_diff/diff_tables.py
> Fixed docstring in diff_tables() (Issue #182)

- data_diff/databases/oracle.py
- data_diff/utils.py
> Bugfix for Oracle - didn't properly handing .rounds attribute. 

- README.md
- data_diff/__main__.py
- data_diff/databases/base.py
- data_diff/databases/database_types.py
- data_diff/databases/databricks.py
- data_diff/databases/mysql.py
- data_diff/diff_tables.py
- data_diff/sql.py
- data_diff/utils.py
Solves issue #83 .
@nolar This one didn't turn out as pretty as I'd like it to be.
Any suggestions? Or maybe it's the least of all evils?
**Explanation:**
We don't want to process column types that the user didn't request, because they might generate irrelevant warnings, or even errors for unsupported types. (and we also query the table for them, to figure out their 'refined' type)
But, we need the schema in order to choose the mutual columns.
And we need the mutual columns to choose which columns to process.
This is cyclical, so I break the cycle by working with "raw" schema until the mutual columns can be figured out.
> Added support for auto-detecting mutual columns, and using patterns in -c

- README.md
Postgresql requires `psycopg2` to be installed. However, to install that some dependencies are required that cannot be installed using pip. Adding some documentation to make users aware and give a simple solution for a test setup.
> Add extra documentation on installing drivers for postgresql

- data_diff/databases/clickhouse.py
- data_diff/diff_tables.py
- tests/common.py
- tests/test_database_types.py
- tests/test_diff_tables.py
> Fixed support for diffing columns of different names

- data_diff/databases/base.py
> Deprecate use of FixedAlphanum

- .github/workflows/ci.yml
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/presto.py
- data_diff/joindiff_tables.py
- data_diff/queries/api.py
- data_diff/queries/ast_classes.py
- data_diff/query_utils.py
- tests/common.py
- tests/test_api.py
- tests/test_cli.py
- tests/test_database_types.py
- tests/test_diff_tables.py
- tests/test_joindiff.py
- tests/test_postgresql.py
- Re-use connections better
- Removes Preql dependency
- Convert code to new query-builder (WIP)
> Refactor tests oct2022

- README.md
* Incorporate feedback from 2022-10-31 Slack discussion:
* Link to GitHub Discussions in README to make it easier for people who aren't in the Locally Optimistic Slack to get in touch.
* Link to GitHub Issues in README to make it easier for people to contribute.
* Update links from readthedocs to Datafold Docs in cases where the content is available in Datafold Docs and not autogenerated from python docstrings.
* Note: we should remove the same content from readthedocs so that it doesn't have to be maintained in two locations.
* Clean up the formatting and wording a bit throughout the README.
> link to docs and incorporate roman/gerard feedback

- data_diff/databases/base.py
- data_diff/databases/database_types.py
- data_diff/databases/mysql.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/snowflake.py
- data_diff/databases/vertica.py
- tests/test_database_types.py
> Added support for Boolean types

- data_diff/__main__.py
> Fix for issue #286

- docs/new-database-driver-guide.rst
Thinking about adding a section on Debugging.  
Not sure which file to use
> New DB Driver guide update

- data_diff/table_segment.py
On my side when dst is a TableSegment object, dst.count() returns an int. Using `data-diff==0.2.8`
> Update typing of TableSegment().count()

- data_diff/tracking.py
Switch tracking from Freshpaint to Rudderstack.
> Rudderstack poc

- data_diff/hashdiff_tables.py
- tests/test_diff_tables.py
Return all duplicated rows in results.
Test tables:
```
DROP TABLE IF EXISTS test_table_1;
CREATE TABLE test_table_1 (
c1 integer,
c2 text
);
INSERT INTO test_table_1(c1,c2)
VALUES
(12, 'ABCDE'),
(12, 'ABCDE');
DROP TABLE IF EXISTS test_table_2;
CREATE TABLE test_table_2 (
c1 integer,
c2 text
);
INSERT INTO test_small_table_2(c1,c2)
VALUES
(4,'ABCDEF'),
(4,'ABCDE'),
(4,'ABCDE'),
(6,'ABCDE'),
(6,'ABCDE'),
(6,'ABCDE');
```
Result before patching:
```
- ('12', 'ABCDE')
+ ('4', 'ABCDEF')
+ ('4', 'ABCDE')
+ ('6', 'ABCDE')
```
Result after patching
```
- ('12', 'ABCDE')
- ('12', 'ABCDE')
+ ('4', 'ABCDEF')
+ ('4', 'ABCDE')
+ ('4', 'ABCDE')
+ ('6', 'ABCDE')
+ ('6', 'ABCDE')
+ ('6', 'ABCDE')
```
> return all duplicated rows

- data_diff/__main__.py
- data_diff/databases/_connect.py
- data_diff/joindiff_tables.py
- data_diff/parse_time.py
- data_diff/sqeleton/abcs/database_types.py
- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/bigquery.py
- data_diff/sqeleton/databases/clickhouse.py
- data_diff/sqeleton/databases/connect.py
- data_diff/sqeleton/databases/databricks.py
- data_diff/sqeleton/databases/duckdb.py
- data_diff/sqeleton/databases/mysql.py
- data_diff/sqeleton/databases/oracle.py
- data_diff/sqeleton/databases/postgresql.py
- data_diff/sqeleton/databases/presto.py
- data_diff/sqeleton/databases/snowflake.py
- data_diff/sqeleton/databases/vertica.py
- data_diff/sqeleton/queries/api.py
- data_diff/sqeleton/queries/ast_classes.py
- data_diff/sqeleton/queries/compiler.py
- tests/common.py
- tests/sqeleton/test_query.py
- tests/sqeleton/test_sql.py
- tests/test_cli.py
- tests/test_database_types.py
- tests/test_diff_tables.py
> data-diff now uses database A's now instead of cli's now.

- data_diff/__main__.py
- data_diff/sqeleton/databases/clickhouse.py
- data_diff/sqeleton/databases/mysql.py
> Better error messages in databases; Default database in clickhouse is now 'default'.

- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/redshift.py
Existing `data-diff` redshift capabilities are unable to read external tables. These are found in the `svv_external_columns` table. 
Original thought was to add a database flag `-e --external-table` but I don't believe flags can be specific to one database connection and not the other. A simpler approach is to simply query the external tables in redshift if none was found in the redshift one.
* Adding `select_external_table_schema` in redshift sqeleton
* Add condition to query redshift external tables if no results were found in the redshift database.
> Add redshift external tables

- data_diff/__init__.py
- data_diff/table_segment.py
The `where` argument was not available in the Python API. This fixes that error of omission to create behavior that's consistent with a) the CLI behavior, and b) the Python API documentation.
> Add 'where' argument to Python API

- README.md
Remove reference to the pre-release, which is no longer relevant, from the README.
> remove reference to pre-release

- data_diff/config.py
- tests/test_config.py
Add env variables support in `.toml` config (https://github.com/datafold/data-diff/issues/278).
Obvious syntax options were:
- `{ENV_VAR}` like Python f-strings or `.format()`.
- `$ENV_VAR` like in shell scripts.
- `${ENV_VAR}` is also widely used. For example, in [docker-compose](https://docs.docker.com/compose/environment-variables/).
I suggest using `${ENV_VAR}`, mainly because: 
- The f-strings-like approach is something I find very Python-specific.
- In contrast to `$ENV_VAR`, we can probably get away without escaping special characters with this approach.
However, I don't mind switching format if, for some reason, `${ENV_VAR}` doesn't work for us.
> Add env variables support in .toml config

- data_diff/dbt.py
- data_diff/diff_tables.py
- data_diff/tracking.py
- data_diff/utils.py
Adds new events for the `--cloud` option
Sets a new entrypoint `CLI-dbt` for `--dbt` and `--cloud`
Added additional parameters to end_event in order to differentiate `--cloud` events
Most of the information is hardcoded to 0/None/etc. on the end event as we don't currently have the related information. Since I think it's likely we will be adding polling and diff results for `--cloud` in the near future, I thought it made sense to reuse the existing event structure.
> Add events for dbt feature

- data_diff/dbt.py
- data_diff/diff_tables.py
My attempt at improving the CLI printout without using any additional python packages.
BEFORE:
AFTER:
TODO based on comments in https://github.com/dlawin/data-diff/pull/3:
> spruce up CLI output in dbt context

- data_diff/dbt.py
- tests/test_dbt.py
Addressing https://github.com/datafold/data-diff/issues/388 .
> reverse order of dev and prod tables in cli printout and cloud diffs

- data_diff/dbt.py
- tests/test_dbt.py
Closes #391 
We are inadvertently raising an exception when specifying only `prod_database:`
Added tests to cover the possible scenarios
Expected (no exception):
```
dbt_vars_dict = {
"prod_database": "prod_db",
"prod_schema": "prod_schema",
"datasource_id": 1,
}
```
```
dbt_vars_dict = {
"prod_database": "prod_db",
"datasource_id": 1,
}
```
Exception
```
dbt_vars_dict = {
"datasource_id": 1,
}
```
```
dbt_vars_dict = {
"datasource_id": 1,
"prod_schema": "prod_schema",
}
```
> fix issue 391 incorrect raise, add tests

- data_diff/dbt.py
- pyproject.toml
- tests/test_dbt.py
> Make DBT dependency optional

- data_diff/__init__.py
- data_diff/dbt.py
- data_diff/diff_tables.py
- data_diff/lexicographic_space.py
- data_diff/sqeleton/repl.py
- data_diff/table_segment.py
- data_diff/utils.py
- tests/test_diff_tables.py
min_key/max_key are now Vectors with a product order, as it has much simpler geometric properties than the previously proposed lexicographic order.
> Compound keys implementation, using product order

- data_diff/dbt.py
Resolves #420 
"Columns exclusive to table A/B" is very literal, and does not immediately convey changes. This PR changes the output to more user friendly  "Columns added/removed" language.
Example change, removing a column and adding a column
Revised output with "Columns added/removed" rather than "exclusive to table A/B"
> revise columns added-removed output

- data_diff/dbt.py
- data_diff/utils.py
- tests/test_dbt.py
Resolves #417 
Moves profiles.yml parsing to a new method `_get_connection_creds`
Adds error handling for the dictionary .gets() while parsing profiles.yml
(Maybe overkill, but having descriptive errors here will add a lot of clarity)
Rework/add related unit tests
> Issue 417 error handling

- data_diff/dbt.py
> Fix multiple Diffs Complete! messages

- data_diff/dbt.py
Resolves #399 
Use model.alias instead of model.name
When config alias is set, it is the correct object name. When config alias is not set, alias == name
> always use model.alias for table path

- poetry.lock
- pyproject.toml
[v0.0.7](https://pypi.org/project/sqeleton/0.0.7/) includes 3-part id support for Databricks, Postgres, DuckDB, and Redshift along with a fix that addresses failing tests on (v0.0.6) other fixes
> bump to sqeleton v0.0.7

- data_diff/dbt.py
- tests/test_dbt.py
> issue 425 parse and use threads

- data_diff/dbt.py
- tests/test_dbt.py
Currently, only the `outputs: \n  <target_name>:` section of the profiles.yml profile has the dbt jinja rendered
Change renders the entire profile instead, specifically to support dbt jinja in `target: `
Closes #386
> render jinja in entire selected profile

- data_diff/dbt.py
Resolves #404 
Adds support for custom schemas, with a new data_diff var
Example (custom schema environments):
```
vars:
data_diff:
prod_schema: BEERS
prod_database: INTEGRATION
```
No need to do anything here, custom_schemas is assumed to be True
prod path = `<prod_database>.<prod_schema>_<custom_schema>.<model>` if the model _has_ a custom schema.
else:
prod path = `<prod_database>.<prod_schema>.<model>`
Setting `custom_schemas: False` would cause the prod comparison path to be `<prod_database>.<prod_schema>.<model>` or `<prod_database>.<same_schema_as_dev_model>.<model>` based on the existence of the `prod_schema` variable (existing behavior).
Example (schema environments):
```
prod_schema: BEERS
prod_database: INTEGRATION
custom_schemas: False
```
prod path = …
> support custom schemas

- data_diff/dbt.py
- data_diff/tracking.py
Adding dbt's user ID to tracking. 
Successful dev event for dbt-CLI
successful dbt cloud event:
Non-dbt event showing null as expected:
> Adding user id to tracking

- data_diff/dbt.py
- data_diff/diff_tables.py
- data_diff/joindiff_tables.py
- data_diff/tracking.py
- tests/test_dbt.py
Add an option of generating of a Datafold API key to interact with a datafold cloud.
If the key is not provided, it is suggested to a user to generate it redirecting to a corresponding datafold cloud page.
Also add an opportunity to set a datafold host (by default it is our cloud url https://app.datafold.com)
> cloud api token flow

- data_diff/dbt.py
- data_diff/diff_tables.py
- data_diff/utils.py
- pyproject.toml
- tests/test_dbt.py
Resolves #460 
This PR expands the output of `--cloud` by polling the datafold api for diff results.
Currently the API does not expose the columns added or removed, so this is a limitation until the api is updated (also in progress).
These screenshots hopefully help illustrate the current state as a comparison (there is a local and --cloud diff in each):
Note the missing added/removed below:
> expand --cloud output by polling for results

- data_diff/dbt.py
- tests/test_dbt.py
Partial resolution for #442 
Supports [this ](https://docs.getdbt.com/reference/warehouse-setups/snowflake-setup#key-pair-authentication)auth method except when `private_key_passphrase` is provided
> add basic snowflake key/pair support

- data_diff/dbt.py
resolves #474 
Before:
`[12:52:44] ERROR - 'NoneType' object has no attribute 'get'`
After:
`[11:13:53] ERROR - No vars found in dbt_project.yml.`
`[11:14:26] ERROR - data_diff: section not found in dbt_project.yml vars:.`
> raise when project vars not found

- data_diff/dbt.py
- data_diff/tracking.py
To help inform product development, adding dbt_version and dbt_project_id to tracking. I followed the same conventions as we did for dbt_user_id.
Test events were successful in the dev Ruddestack space:
> dbt tracking

- data_diff/dbt.py
> Issue 489: do not infer source pks from tests

- data_diff/dbt.py
- tests/test_dbt.py
Resolves #413 
It seems to be this simple, but I don't have a great way to test it at the moment
> add snowflake sso

- data_diff/cloud/__init__.py
- data_diff/cloud/data_source.py
- data_diff/cloud/datafold_api.py
- data_diff/dbt.py
- data_diff/tracking.py
- dev/_bq_import_csv.py
- tests/cloud/files/data_source_list_response.json
- tests/cloud/files/data_source_schema_config_response.json
- tests/cloud/test_data_source.py
- tests/test_dbt.py
- tests/test_diff_tables.py
Add functions to create a new data source via the data diff CLI
1. Create a new data source if it does not exist neither in the datafold cloud nor in the `dbt_project.yml`
[Screencast from 30.03.2023 17:58:04.webm](https://user-images.githubusercontent.com/22893396/228829154-144de2d6-d6b2-44cc-a6db-f813c27be346.webm)
2. Use an existing data source in the cloud if it is not set in `dbt_project.yml`
[Screencast from 30.03.2023 18:11:30.webm](https://user-images.githubusercontent.com/22893396/228832386-6800b3d6-3868-4597-853c-2fd18bfd0592.webm)
> Datafold database credentials from cli

- README.md
- docs/common_use_cases.md
- docs/usage_analytics.md
There were several broken and/or irrelevant links since the launch of docs.datafold.com 3.0, as well as an outdated Loom.
> fix up links in readme

- data_diff/dbt.py
- tests/test_dbt.py
To (hopefully) cover all custom schemas scenarios I've reworked some of the data_diff variables in dbt_project.yml
```
vars:
data_diff:
prod_database: analytics-383622
prod_schema: prod # default
prod_custom_schema: prod_<custom_schema> # falls back to default when there is no custom schema
```
- **Removed** custom_schemas boolean
- **Added** `prod_custom_schema`
- When a model has a custom schema, the `<custom_schema>` will be replaced with the custom schema name
- Using the example above
- `config(schema = 'marketing')` -> `analytics-383622.prod_marketing.model`
- No custom schema -> `analytics-383622.prod.model`
Additional examples:
```
vars:
data_diff:
prod_database: analytics-383622
prod_schema: prod # default
prod_custom_schema: <custom_schema> # falls back to default when there is …
```
> handle all custom schemas scenarios

- data_diff/cloud/datafold_api.py
- data_diff/dbt.py
- tests/test_dbt.py
It can be unclear when using `--cloud` that "things are happening"
- Add diff links right away and and "in progress" message
- shorten max_sleep_interval on diff results polls to 30 sec
This will make it more clear that "things are happening", allow users to immediately pull up the diff in the UI, and shorten the max time for results to display
https://www.loom.com/share/9d9c504703de44998dca3a282c43b2e7
> Cloud diffs in progress

- data_diff/dbt_parser.py
- tests/test_dbt.py
Resolves #516 
Warn when using a recent dbt-core version instead of throwing an exception:
> warn when using recent dbt-core version

- data_diff/dbt_parser.py
This PR resolves #499
Added log statements that will be indicating the current artifact being parsed in debug mode.
```INFO:hashdiff_tables:. Diffing segment 2/2, key-range: (6c9f2344-de9b-11ed-a3a6-000000000019)..(6c9f2b64-de9b-11ed-afba-000000000032), size <= 329589156059341385030398812094514
INFO:dbt_parser:Parsing file target/run_results.json
.INFO:diff_tables:Diffing segments at key-range: (1)..(51). size: table1 <= 50, table2 <= 50
INFO:dbt_parser:Parsing file dbt_project.yml
```
```
.....INFO:dbt_parser:Parsing file target/run_results.json
.....INFO:diff_tables:Diffing segments at key-range: (6c9f1b24-de9b-11ed-9792-000000000000)..(6c9f2b64-de9b-11ed-afba-000000000032). size: table1 <= 329589156059341385030398812094514, table2 <= 329589156059341385030398812094514
```
> Add logs to indicate current artifact being parsed in debug mode

- data_diff/cloud/datafold_api.py
- data_diff/dbt.py
- tests/test_dbt.py
Adds support for the meta filter described here:
https://docs.datafold.com/guides/dbt_advanced_configs#filter-tables
The filter expression is applied to both sides of the diff
Resolves partially: #518
> support datadiff meta filter

- data_diff/dbt.py
- tests/test_dbt.py
Seems this was duplicated at some point. See https://github.com/datafold/data-diff/blob/master/data_diff/dbt_parser.py
> remove duplicated consts and methods

- data_diff/sqeleton/abcs/__init__.py
- data_diff/sqeleton/abcs/database_types.py
- data_diff/sqeleton/abcs/mixins.py
- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/oracle.py
- data_diff/sqeleton/databases/postgresql.py
- data_diff/sqeleton/databases/redshift.py
This is a follow-up for #485 for the remaining 3 changes that were merged afterwards:
* https://github.com/datafold/sqeleton/pull/28
* https://github.com/datafold/sqeleton/pull/27
* https://github.com/datafold/sqeleton/pull/15
Now, we can archive Sqeleton safely.
> Follow-up the sqeleton-to-datadiff embedding

- tests/test_database_types.py
This is a follow-up for #383 (which needs to be rebased after the merge; created for CI-driven development with the full test suite executed).
> Fix & extend the tests for JSON/JSONB columns

- data_diff/utils.py
Current version is broken, when calling `utils.diffs_are_equiv_jsons`, `hashdiff_tables.diff_sets` is expecting to have always 2 values to unpack and the early return in the function outputs a single boolean.
When adding the warning feature, I forgot to change the early return to match the function's signature.
> Hotfix: Correct early return in diffs_are_equiv_jsons not including the set object

- data_diff/hashdiff_tables.py
- data_diff/sqeleton/abcs/__init__.py
- data_diff/sqeleton/abcs/database_types.py
- data_diff/sqeleton/abcs/mixins.py
- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/postgresql.py
- data_diff/sqeleton/databases/redshift.py
- data_diff/utils.py
A quick follow-up on #543 to simplify JSON column types before it is released. 
In #533, similar types will follow — `Struct` & `Array`. 
But we should better not bind these changes by time.
> Simplify JSON column types

- data_diff/sqeleton/abcs/database_types.py
- data_diff/sqeleton/abcs/mixins.py
- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/bigquery.py
- data_diff/sqeleton/queries/ast_classes.py
- tests/sqeleton/test_query.py
An attempt to make BigQuery's `ARRAY` & `STRUCT` column types suitable for comparison.
As of now, they are not supported at all, and data-diff does not even understand this type of columns. So the addition will only affect BigQuery and no other databases.
The comparison is rather simplistic — convert to JSON (lists & dicts correspondingly) and try to hash & compare those instead of the real arrays & structs.
This might be affected by different serialization results, such as different key ordering, different spacing & indenting in json, so on. This problem is to be solved separately in https://github.com/datafold/sqeleton/pull/15.
Addresses: https://github.com/datafold/data-diff/issues/445
> Compare JSON, ARRAY, STRUCT types in BigQuery (simplistically)

- data_diff/dbt_parser.py
Without setting this flag, we're seeing an exception in dbt 1.5
Assuming it will not hurt earlier versions to set it
```
File "/Users/dan/Library/Caches/pypoetry/virtualenvs/data-diff-gej9eYRL-py3.10/lib/python3.10/site-packages/dbt/clients/jinja.py", line 102, in _compile
macro_debugging = get_flags().MACRO_DEBUGGING
AttributeError: 'Namespace' object has no attribute 'MACRO_DEBUGGING'
```
> instantiate MACRO_DEBUGGING global for dbt

- data_diff/dbt_parser.py
dbt ls exceptions were being obfuscated by 
`"No dbt models found for `--select {dbt_selection}`"`
> if dbt ls throws an exception, raise that first

- README.md
Updating the README to have database-specific instructions for dbt users until such time as `pip install data-diff` will "just work."
> add database-specific installation instructions to readme

- data_diff/dbt.py
- tests/test_dbt.py
Resolves #530
This will also make the `prod_database:` field in dbt_project.yml optional. When that is not included, use the database from the local manifest.json (prod_db == dev_db)
This can be `None` for some dbt adapters like Databricks, so `None` values are filtered out.
> add support for two part id

- .github/workflows/triage_labels.yml
Creating a workflow to add a `triage` label to new and reopened issues
borrowed from here:
https://docs.github.com/en/enterprise-cloud@latest/actions/managing-issues-and-pull-requests/adding-labels-to-issues
> add triage labels workflow

- README.md
Clay pointed out that for people who are interested in XDB, this is a more appropriate docs link than the simple list of supported databases.
> link to docs.datafold.com for XDB

- .github/workflows/stale.yml
adding double quotes to deal with apostrophes in message
> stale yml error

- data_diff/dbt_parser.py
I thought the error message, while really good already, could use some extra love. 
Specifically, I wasn't sure exactly what the next step was, even though the message made it very clear what the _problem_ and the _solution_ was (but not the tactical steps to solve the problem).
> update --select dbt version error message

- .github/workflows/stale.yml
https://github.com/actions/stale#labels-to-add-when-unstale
If a stale issue/PR has activity (comment etc), the `stale` label will be removed and a `triage` label added.
> add triage label to unstale issues/PRs

- data_diff/cloud/datafold_api.py
- data_diff/dbt.py
- data_diff/dbt_parser.py
- tests/test_dbt.py
Datafold API attempts to infer the correct casing based on the presence of tables in the schema. However, to avoid unnecessary SQL queries to the user database, we should provide the correct casing whenever possible. Currently we do that only for client-side diffs but not for `--cloud` diffs.
> Use proper casing policy for --cloud diffs

- data_diff/sqeleton/databases/_connect.py
Currently, when oracle DSN is provided with a port, e.g. `oracle://localhost:1234/db`, the cx_Oracle driver will report
```
'port' is an invalid keyword argument for this function
```
Accordding to the [docs](https://cx-oracle.readthedocs.io/en/latest/user_guide/connection_handling.html#easy-connect-syntax-for-connection-strings), cx_Oracle support port in `dsn` parameter:
> If the database is using a non-default port, it must be specified:
> ```
> connection = cx_Oracle.connect(user="hr", password=userpwd,
>                                dsn="dbhost.example.com:1984/orclpdb1",
>                                encoding="UTF-8")
> ```
This PR parses port from data-diff into host of cx_Oracle, thus supports port number in oracle connection.
close #370
> support "port" in oracle connection

- data_diff/dbt.py
- data_diff/utils.py
- tests/test_dbt.py
Resolves #542 
When the type differs between dev <> prod, don't attempt to diff and output that the type has changed. Example:
This brings local diffs into alignment with `--cloud` in regard to type changes
> handle column type changes

- data_diff/__init__.py
- data_diff/dbt.py
- data_diff/joindiff_tables.py
- tests/test_dbt.py
Adds a skip_null_keys option to joindiff (default False)
When set to True, instead of throwing an error and exiting the diff, a warning is displayed and the diff continues (row is skipped).
Added for `--dbt` diffs to resolve #527
> continue --dbt diff when null PKs exist

- data_diff/dbt.py
- data_diff/dbt_parser.py
- data_diff/utils.py
Adds a message when a new data-diff version is available
Up-to-date:
Not up-to-date:
> add warning when using outdated data-diff version

- data_diff/dbt.py
- tests/test_dbt.py
Resolves #483 
It's possible to set databases in model configs or model .yml, use this value for the "prod database" when it is present, otherwise fall back to the existing logic.
Old:
config db > dev db
New:
custom db > config db > dev db
Added new unit test `test_get_diff_vars_custom_db` to verify `model.config.database` is used for prod_path when present.
> add support for custom database config

- data_diff/dbt_parser.py
- data_diff/errors.py
- data_diff/utils.py
- tests/test_dbt.py
Changes this module to not use generic exception types so error events can be more understandable.
Also involved changing utils.get_dict_with_raise to accept an exception parameter
> Add custom exceptions for raises in dbt_parser

- .github/workflows/stale.yml
Stale issues are being closed as "completed" at the moment. Update to "not_planned"
https://github.com/actions/stale#close-issue-reason
> set close reason to not_planned for stale issues

- data_diff/__main__.py
Support paths like `~/.dbt` as `--dbt-profiles-dir` and `--dbt-project-dir` parameters.
> expand ~ in dbt paths

- data_diff/__main__.py
- data_diff/cloud/data_source.py
- data_diff/dbt.py
- data_diff/dbt_parser.py
- data_diff/errors.py
- tests/cloud/test_data_source.py
- tests/test_dbt.py
Adds a new flag `--state` for use with the dbt integration
A user can use this flag to specify the "production" manifest location e.g.:
`data-diff --dbt --state ~/prod_manifest.json`
This removes the need for configuration in the dbt_project.yml, and covers scenarios not covered via configuration. The prod manifest is used as the source of truth for production model locations vs. via configuration.
Changes:
- added `prod_manifest_obj` to DbtParser
- renamed `manifest_obj` in DbtParser to `dev_manifest_obj` to differentiate
- Renamed `DbtParser.get_datadiff_variables` to `DbtParser.get_datadiff_config` (this was easily confused with _get_diff_vars)
- Altered to return a TDatadiffConfig object vs. the previous dictionary
- get_manifest_obj altered to be generic (can be used for any path) 
- …
> add --state flag feature to dbt integration

- data_diff/dbt_parser.py
- data_diff/errors.py
- data_diff/sqeleton/databases/bigquery.py
- tests/test_dbt.py
Adds support for the [Service Account File](https://docs.getdbt.com/docs/core/connect-data-platform/bigquery-setup#service-account-file) dbt profile config
Resolves #595
> --dbt add support for BQ service-account

- poetry.lock
- pyproject.toml
dsnparse has a breaking change in >= 0.2.0 see #616 
@pik94 @nolar, I saw a related convo [here](https://github.com/datafold/data-diff/pull/492/commits/1b214d64901b082d521b693b320fbc69987aacd4#r1162794271), so interested in your thoughts.
We could instead set the version to `>= 0.2.0` and make corresponding changes, but it seems from your convo that would rule out support for Python 3.7
Alternatively, we could not use this package... but this seemed like the simplest fix for now.
Resolves #616
> set upper limit on dsnparse version

- data_diff/__main__.py
- data_diff/cloud/datafold_api.py
- data_diff/dbt.py
- data_diff/utils.py
- tests/test_dbt.py
Improves the `--debug` log readability by using [RichHandler](https://rich.readthedocs.io/en/stable/logging.html). This format is also used without the debug flag for warnings and errors
Adds a new custom logging handler LogStatusHandler. This is used to display diff status and some detail for local and cloud `--dbt` diffs.
Local dbt diff:
Cloud dbt diff:
Started (it's not ideal doubling some of the info here, but it seems a rich.status.Status can't display a clickable link... otherwise one line would be great per model)
One completed
> log improvements and display diff status

- data_diff/diff_tables.py
Addresses https://github.com/datafold/data-diff/issues/629, bug(?) that caused "Rows Added" and "Rows Removed" to be reversed in the `--dbt` CLI printout.
> fix reversal of rows added and removed

- data_diff/diff_tables.py
- data_diff/format.py
We used to count differences across all rows for the "diffCounts" metric, even added/removed rows, for `--json` output format. Replaced that with `extra_column_diffs` value — the one we currently use for normal output.
**Normal output**
**--json**
```
{
"status": "success", 
"result": "different", 
"model": "model.dbt_valentin_snowflake.downstream_different_from_row_diff", ..., 
"stats": {"diffCounts": {"VALUE": 3}}},
...
}
```
> include only rows with equal PK to values diff stats in --json output

- data_diff/diff_tables.py
- tests/test_api.py
Fix `get_stats_dict` function so that `values` dict is always there to avoid possible KeyErrors.
> fix KeyError exception for --json diffs

- data_diff/format.py
- tests/test_format.py
Fix exceptions when using `--json` for datasets including columns with `_a` or `_b` in the name
<details>
<summary>traceback</summary>
```
ERROR    Field dataset1 requires a value                                                                                                         __main__.py:326
Traceback (most recent call last):
File "/Users/dan/repos/demo/env/bin/data-diff", line 8, in <module>
sys.exit(main())
^^^^^^
File "/Users/dan/repos/demo/env/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/dan/repos/demo/env/lib/python3.11/site-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/Users/dan/repos/demo/env/lib/python3.11/site-packages/click/core.py", …
```
> fix crashing when parsing column names including _a, _b

- data_diff/cloud/datafold_api.py
- data_diff/errors.py
Poll more frequently when using `--dbt --cloud`
Biggest change is that the backoff is now additive, it just increases by 1 sec each iteration to a max of 20 sec vs. the former doubling.
Also created custom exceptions for existing generic exceptions since I was in there.
> poll more frequently when using --cloud

- data_diff/dbt_parser.py
Resolves https://github.com/datafold/data-diff/issues/645
This PR fixes an issue with the `profiles_dir` provided in the cli arguments being overwritten for DBT versions < 1.3.0, even though it should take precedence.
This will also cover the case when the `DBT_PROFILES_DIR` env var is set, as that's handled by click and should come in the `profiles_dir_override` argument.
> fix profile_dir argument overwritten by legacy dir for DBT < 1.3.0

- data_diff/dbt.py
- tests/test_dbt.py
Resolves https://github.com/datafold/data-diff/issues/646
Currently the model alias is extracted from the run_results file even when the manifest file is provided, which doesn't allow to use data-diff when the prod aliases are different.
This PR modifies this behaviour and extracts the prod aliases from the manifest file when provided.
> get prod alias from manifest file when provided

- data_diff/sqeleton/databases/postgresql.py
- tests/test_postgresql.py
Postgres does not allow functions that have more that have more than 100 arguments. When using the concat function, this limits comparisons to less than 50 fields.
Using `||` for concat like the Oracle variant fixes this.
> Fix for more than 50 fields in Postgres

- README.md
dbt devs should be directed to https://docs.datafold.com/development_testing/open_source/ instead of being presented with the vanilla `data-diff` CLI instructions for getting started. 
With this PR, we'll have essentially separate "getting started" notes for the XDB vs dbt use cases, which don't overlap and have very different user personas.
> clarify getting started for dbt vs xdb

- data_diff/__main__.py
- data_diff/dbt_parser.py
- data_diff/errors.py
- tests/test_dbt_parser.py
This PR allows `--select` to work with dbt versions < 1.5, but in a much simpler manner
Example on a version < 1.5:
`--select <some_input>`
The manifest is searched for `<some_input>` directly regardless of any dbt selectors like `+, @` or multiple model names `model_1 model_2`. In the latter example, it would search the manifest for a single model named `model_1 model_2`
I've included a warning to help make this clear. See:
> partial --select support for dbt < 1.5

- data_diff/databases/__init__.py
- data_diff/databases/_connect.py
- data_diff/databases/mssql.py
- data_diff/joindiff_tables.py
- data_diff/sqeleton/abcs/database_types.py
- data_diff/sqeleton/databases/__init__.py
- data_diff/sqeleton/databases/_connect.py
- data_diff/sqeleton/databases/base.py
- data_diff/sqeleton/databases/mssql.py
- data_diff/sqeleton/databases/oracle.py
- data_diff/sqeleton/queries/ast_classes.py
- poetry.lock
- pyproject.toml
- tests/common.py
- tests/sqeleton/common.py
- tests/sqeleton/test_database.py
- tests/sqeleton/test_query.py
- tests/test_database_types.py
> Support MSSQL for cross-database diffs

- data_diff/sqeleton/databases/_connect.py
- data_diff/sqeleton/utils.py
- tests/sqeleton/test_utils.py
As a part of the series of simplifications, basically as a preliminary warmup/cleanup: remove unnecessary entities & abstractions.
> Simplify by replacing the self-made WeakCache with the builtin WeakValueDict

- data_diff/__init__.py
- data_diff/__main__.py
- data_diff/abcs/compiler.py
- data_diff/abcs/database_types.py
- data_diff/bound_exprs.py
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/databricks.py
- data_diff/joindiff_tables.py
- data_diff/queries/ast_classes.py
- data_diff/queries/compiler.py
- data_diff/queries/extras.py
This PR inverses the flow of AST-to-SQL compilation. 
Previously, it was going from the root code -> database -> compiler -> AST nodes, which in turn sometimes (but not always) redirected back to the compiler -> dialect for some pieces of SQL.
As a result, the SQL logic was spread over the code base and was difficult to override per database.
Now, the root code goes -> database -> compiler -> dialect directly. The dialect knows how to render all SQL. Specifically, the base dialect provides the core SQL for all databases, with each and every AST node being possible to override. The AST nodes know nothing about SQL, they only express our intentions of what should be executed, not how.
A very simple chart:
> Compile all AST elements always via dialects, never directly

- data_diff/__main__.py
- data_diff/databases/_connect.py
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/snowflake.py
- data_diff/databases/vertica.py
- data_diff/format.py
- data_diff/joindiff_tables.py
- data_diff/queries/ast_classes.py
- data_diff/schema.py
- data_diff/table_segment.py
- data_diff/utils.py
- tests/common.py
- tests/test_database.py
- tests/test_database_types.py
- tests/test_dbt_parser.py
- tests/test_format.py
- tests/test_joindiff.py
- tests/test_query.py
- tests/test_sql.py
The recent batch of refactoring (#703, #704, #707, #708, #709, #710, #713, #714) has broken a few things all over the code (mostly imports & class references).
This PR should fix it all to the extent the tests do pass.
The following PR #723 should make it nice.
Supersedes #719 & #721.
> Fix the aftermath of refactoring

- data_diff/__main__.py
- data_diff/databases/postgresql.py
- tests/test_cli.py
```
File "/Users/dan/repos/dbt-analytics/.venv/lib/python3.11/site-packages/data_diff/__main__.py", line 485, in _data_diff
if db1 == db2:
^^^^^^^^^^
File "<attrs generated eq data_diff.databases.postgresql.PostgreSQL>", line 13, in __eq__
AttributeError: 'PostgreSQL' object has no attribute '_conn'
```
> 'PostgreSQL' object has no attribute '_conn'

- data_diff/utils.py
This should have been caught by type checking, but we miss the latter yet (moving in that direction).
> Unhide the implemented methods for ordering & repring the arith-texts

- data_diff/databases/mssql.py
As a rule, `super().__init__()` **MUST**:
* Always be called (never skipped; especially with this complex system of mixins).
* Always be called before anything else is set on the object.
Otherwise, the parent class'es constructor overwrites the properly pre-initialized `self.default_schema` to `None`, and this breaks the table name resolution.
> Call parent's init before field initialisation, not after

- data_diff/dbt_parser.py
When running with dbt Cloud artifacts, I came across the error below.
```shell
Running with data-diff=0.9.2
10:28:28 ERROR    'NoneType' object has no attribute 'name'                                                                                                                                                                                                 __main__.py:329
Traceback (most recent call last):
File "/Users/sung/public-api-demos/venv/bin/data-diff", line 8, in <module>
sys.exit(main())
File "/Users/sung/public-api-demos/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
File "/Users/sung/public-api-demos/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
File …
```
> Check if `test_metadata` Exists First

- README.md
- data_diff/__main__.py
- data_diff/joindiff_tables.py
- data_diff/utils.py
- tests/test_joindiff.py
- tests/test_utils.py
Get duckdb/motherduck to work with data-diff using `joindiff` within the `dbt-core` integration. 
Right now, it defaults to `hashdiff` which is not as performant. 
Scrub sensitive motherduck tokens in logs.
Known Limitation with [SaaS only mode](https://motherduck.com/docs/authenticating-to-motherduck/#authentication-using-saas-mode) in that it will not work with data-diff. We'll have to change multiple query runner functions to avoid race conditions which is outside the scope of this PR. 
```shell
~/De/data-diff/datafold-demo-sung  demo-pr !1 ?1  data-diff --conf datadiff.toml --run demo_xdb_duckdb -k "id" -c status --debug 
12:31:03 DEBUG    Applied run configuration: {'verbose': False, 'database1': {'driver': 'duckdb',         __main__.py:296
'filepath': …
```
> Make DuckDB data diffs work better

- data_diff/databases/__init__.py
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/redshift.py
- data_diff/databases/snowflake.py
- data_diff/databases/vertica.py
- tests/common.py
We utilize a portion of the MD5 checksum, specifically 6 bytes per row, to allow for the accumulation of more rows before encountering overflow. However, in most databases, hex numbers are padded with zeros if they are not 8 bytes long. For example, `0xFF` becomes `0x00000000000000FF`.
Since the most significant bit is always 0, the number is consistently positive. Consequently, there is a limit to the number of values we can sum before encountering overflow in the bigint type.
To address this limitation, we introduce a negative offset equal to half of the maximum checksum number. This adjustment expands the range of values to "-max number/2" to "+max number/2". By incorporating negative numbers, we can offset some of the positive ones, enabling the summation of more numbers without …
> add checksum offset to avoid bigint overflow

- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/redshift.py
- data_diff/databases/snowflake.py
- data_diff/databases/trino.py
- data_diff/databases/vertica.py
_Little improvements step by step:_
This time, squash the database-specialised mixins into their corresponding database-specialised dialects — since these mixins are not reused anywhere else.
In particular, resolve the Postgres-Redshift & Presto-Trino pairs with double inheritance of the same methods (first, inherited from the parent dialect class; second, inherited from the parent mixins, which are already included in the parent dialect class).
_This PR does NOT touch the "abstract" mixins **yet** — to be made later (they are not currently included in the base Dialect class, so this change will need extra care)._
**Reviewer hints:** There are no changes in the code & logic itself, but only moves of methods up & down between classes. The big green & red diffs are there because of how git …
> Simplify: Squash database-specialised mixins into their database-specialised dialects

- data_diff/abcs/mixins.py
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/snowflake.py
- data_diff/databases/vertica.py
- data_diff/queries/ast_classes.py
- tests/test_database.py
_Little improvements step by step:_
**Random sampling** & **time traveling** AST nodes, methods and mixins are not used in the codebase at all. We can safely remove them. When and if needed, we will restore and reimplement them.
The **schema fetching** is a bit more complicated: there are 2 schema fetching logics in the code. The one that is actually used is  `Database.select_table_schema()` & `Database.query_table_schema()`. The one in the mixins (`list_tables()` & `table_information()`) is unused. Hence, we can remove it too.
On a matter of whether we want to move the schema fetching from databases to dialects: probably not. Some databases can expose their schemas via non-SQL APIs, such as HTTP API, so it should remain in the database. The dialect should only do the SQL rendering. If we …
> Simplify: Remove unused code & mixins

- data_diff/databases/databricks.py
- data_diff/databases/mssql.py
Otherwise these default to varchar (fixed length)
> update str type_reprs for mssql, databricks

- .github/workflows/formatter.yml
Currently, review dog will add suggestions, but the step is always green. Update to fail the CI job on bad formatting
> Block merge on formatter error

- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/mysql.py
- data_diff/databases/oracle.py
- data_diff/databases/postgresql.py
- data_diff/databases/presto.py
- data_diff/databases/redshift.py
- data_diff/databases/snowflake.py
- data_diff/databases/trino.py
- data_diff/databases/vertica.py
- data_diff/diff_tables.py
- tests/test_joindiff.py
- tests/test_query.py
Some databases, for example, Teradata, have a short limit for string and requires to set a number of symbols in `CHAR/VARCHAR`, i.e. it is required to write it like this
```
CREATE TABLE MyTable (
col_name VARCHAR(n)
)
```
where `n` must be set and has some max allowed value.
To calculate md5 hash and convert it to an integer value, values of columns for one row are cast to strings, and concatenated afterwards. Let me clarify on an example:
```
CREATE TABLE MyTable (
id INTEGER,
data VARCHAR(n)
)
```
To concatenate we use a construction like this:
```
CAST(id AS VARCHAR(n1)) || '|'  || CAST(data AS VARCHAR(n2)) 
``` 
The question is what should `n1` and `n2` be? I am sure that the maximum allowed value for a specific type, for example, `N`. It is needed to keep all customer information …
> Prevent type overflow

- data_diff/databases/databricks.py
- data_diff/databases/redshift.py
- data_diff/schema.py
See commits/extended commit messages
> Normalize schema info databricks redshift

- data_diff/databases/databricks.py
would need to update process_table_schema as well
> revert databricks information_schema

- .gitignore
- README.md
The current link (re)directs to:
But more logical is to go to:
> Chiel fix link readme

- data_diff/databases/base.py
- data_diff/databases/postgresql.py
- data_diff/databases/redshift.py
Update redshift/postgres normalize_timestamp to handle all possible values
https://www.postgresql.org/docs/current/datatype-datetime.html
- Technically rounds BC timestamps the wrong way
- Edge case at the upper/lower bounds, rounded to keep below overflow
- the least() and greatest()
Resolves #786
> Handle full timestamp ranges for redshift, postgres

- data_diff/dbt_config_validators.py
this causes validation errors
e.g.
```
nodes -> test.test_name.dbt_utils_unique_combination_of_columns-> database
none is not an allowed value (type=type_error.none.not_allowed)
```
> databricks does not require "database"

- data_diff/databases/mssql.py
two problems:
- TRIM requires a CAST to char
- the TRIM not providing an alias causes problems when the TRIM is part of a nested query
> mssql normalize_uuid

- data_diff/databases/mssql.py
normalize_uuid change was just a symptom of problem with mssql's limit_select
- revert normalize_uuid change
- fix limit_select for mssql
> Revert "mssql normalize_uuid" and fix the overall problem

- data_diff/joindiff_tables.py
resolves #797 
Removes extra logging that was leftover in a previous merge. It doesn't add value to debug logging.
> Remove Unneeded Logging

- README.md
- data_diff/dbt.py
Point users to an evolved CLI experience by trialing Datafold Cloud. 
@KiraFuruichi @leoebfolsom  Included you to verify that's a good entrypoint URL and language call out. If you approve, I can simply squash and merge as this code change is cosmetic.
> Better Action Next Step when using CLI

- .github/workflows/formatter.yml
- data_diff/databases/mysql.py
Saw this error pop up in #812 It'll now get the head of the PR branch even if it's a forked repo
> Fix github action that doesn't work with forked branches

- data_diff/databases/mysql.py
- data_diff/databases/postgresql.py
- tests/test_postgresql.py
resolves #811 
1. fix special characters in PG url password
2. fix mysql connection not available after a long idle time
> [to#811]Fix special characters in PG url and Mysql connection reconnect

- data_diff/diff_tables.py
- data_diff/thread_utils.py
Add an optional parameter `yield_list` to differ
Setting `yield_list` to True allows the diffs to be consumed as a list -- which is how the diffs are actually generated. That list represents the diffs found over a key range.
> yield list vs. indiv tuples

- data_diff/__main__.py
- data_diff/abcs/database_types.py
- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/clickhouse.py
- data_diff/databases/databricks.py
- data_diff/databases/duckdb.py
- data_diff/databases/mssql.py
- data_diff/databases/oracle.py
- data_diff/databases/presto.py
- data_diff/databases/redshift.py
- data_diff/databases/snowflake.py
- data_diff/databases/vertica.py
- data_diff/dbt.py
- data_diff/schema.py
- data_diff/table_segment.py
- tests/test_dbt.py
~_Requires #813 because of a minor merge conflict; otherwise independent._~
_A replay for #804, which did not run CI for some reason._
> Retrieve collations from the schema (and refactor the column info structures)

- data_diff/databases/mssql.py
Otherwise, it fails with something like this in tests:
```
sql_code = 'SELECT min(CONVERT(varchar, [col])), max(CONVERT(varchar, [col])) FROM [src_mssql_uniqueidentifier_postgresql_char100_50_rrp16]'
data_diff.databases.base.QueryError: ('42000', '[42000] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Insufficient result space to convert uniqueidentifier value to char. (8170) (SQLExecDirectW)')
```
That's because it cannot convert a 36-symbol UUID to 30-symbol varchar. MS SQL Server uses the default length of 30 if other length is not specified.
> Cast to unlimited varchars in MS SQL (especially UUDS)

- data_diff/abcs/database_types.py
- data_diff/databases/base.py
- data_diff/diff_tables.py
- data_diff/table_segment.py
- data_diff/utils.py
- poetry.lock
- tests/test_mesh.py
Comparing MD5s as UUIDs does not work anyway: it improperly slices and then compares the values, since our code always renders UUIDs as `abcdabcd-abcd-abcd-abcd-abcdabcdabcd`, always dashed and lower-cased, while the actual value stored in MD5 (i.e. string) PKs can be uppercased and typically non-dashed (e.g. `ABCDABCDABCDABCDABCDABCDABCDABCD`). As a result, all such MD5 PKs go into one pseudo-UUID range, usually the first one (because in ASCII & UTF-8, uppercase is lesser than lowercase letters).
The root cause is that Python's UUID can parse even such values:
```python
In [3]: from hashlib import md5
In [8]: s=md5(b'hello').hexdigest()
In [9]: s
Out[9]: '5d41402abc4b2a76b9719d911017c592'
In [10]: from uuid import uuid4, UUID
In [11]: UUID(s)
Out[11]: …
```
> Do not detect MD5s as UUIDs, and preserve UUID casing for UUID PKs

- data_diff/databases/databricks.py
Precision and scale are stripped from DECIMAL(precision, scale) here:
```
row_type = "DECIMAL" if info.data_type.startswith("DECIMAL") else info.data_type
info = attrs.evolve(info, data_type=row_type)
```
But are parsed below. Retain this info as a quick fix
> keep precision, scale info for databricks decimal

- data_diff/hashdiff_tables.py
This can cause a ton of false positives
> fix typo -> ignored_columns2=self.ignored_columns2

- data_diff/databases/base.py
- data_diff/databases/bigquery.py
- data_diff/databases/duckdb.py
- data_diff/databases/postgresql.py
- data_diff/databases/vertica.py
- tests/test_database.py
In Postgres, if type is specified as `NUMERIC` (no scale/precision parameters), the effective scale is 16383 ([docs](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-TABLE)).
In BigQuery, the effective scale in this case is 9 ([community forum](https://www.googlecloudcommunity.com/gc/Databases/What-s-default-Scale-and-Precision-of-Numeric-type-in-BigQuery/m-p/612292#M1281)).
> Fix precision recognition

- README.md
The front page of the open source tool needs some refinement and polish to entice new users and show the world we mean serious business!
> Update README to be ergonomic and excite new users

- README.md
- poetry.lock
- pyproject.toml
Update docs to reflect that MS SQL is supported by data-diff
> Microsoft SQL Server Support Docs

- data_diff/diff_tables.py
- data_diff/tracking.py
- poetry.lock
Fix these exceptions
`Exception in thread Thread-1 (send_event_json):`
`TypeError: Object of type lock is not JSON serializable`
`TypeError: Object of type set is not JSON serializable`
> Send event json errors

- data_diff/databases/redshift.py
Add mapping for int and float from Redshift Spectrum.
> LAB-271 Redshift Spectrum type mapping

- data_diff/hashdiff_tables.py
- tests/test_diff_tables.py
A known flaw: if there are equal duped rows, e.g.:
```
A: [pk=1000, val=hello], [pk=1000, val=hello]
B: [pk=1000, val=hello], [pk=1000, val=hello]
```
… then we might not notice them even on the level of checksum scanning of table segments. If the segments are fully equal, these dupes will never be yielded, neither with `-/+`, nor with a potentially different informational marker `*` introduced specially for dupes. It will only be noticed in segments that have some other (unrelated) differences. Which makes this dupe-detection not fully reliable.
> Detect duplicate rows on each side

- data_diff/diff_tables.py
- data_diff/errors.py
* Add error type `DataDiffMismatchingKeyTypesError` for diffs with PK columns of different types. 
* Make the error message more clear: show column names instead of internal types representation.
> Improve error reporting for PK type mismatch

- data_diff/databases/databricks.py
- data_diff/databases/mssql.py
Add proper type mappings for mssql, databricks "date" types.
> Fix mssql, databricks date types

- README.md
SQL Server support is limited, leading to significantly slower performance in any non-trivial use case. This performance issue is addressed in Datafold Cloud.
> clarify that SQL Server support is limited
