README.md

On my laptop it's slower, of course, but at least it's an updated output.
Current one is many many commits ago.

Fixed README sample output

---

README.md
docs/index.rst

I had to adjust this to get the the import to work.

README: fix error in Python import statement

---

data_diff/database.py

@erezsh right now with the errors it's not clear which table is problematic, this helps a little bit

database: include database name in error

---

data_diff/__main__.py
data_diff/databases/base.py
data_diff/databases/database_types.py
data_diff/databases/mysql.py
data_diff/table_segment.py
data_diff/utils.py
tests/test_diff_tables.py

- Added is_distinct_from() method
- Added tests for case-aware mapping
- Fix for CaseInsensitiveDict
- Refactored create_schema()

Refactors and fixes

---

README.md

View the new README here: https://github.com/datafold/data-diff/tree/we-are-hiring#readme

Added a "we are hiring" paragraph to the README

---

data_diff/__main__.py
data_diff/diff_tables.py
data_diff/thread_utils.py

- KeyboardInterrupt is now handled correctly.
- Resulting iterator is now better behaved (--limit works a lot better)

Re-wrote threading to use a thread-pool + priority queue.

---

data_diff/config.py

Added support for specifying db-name in CLI instead of URI when using --conf 

---

data_diff/diff_tables.py

This could happen if the primary key is not unique, and contains a large number of identical rows, N > bisection_threshold .

Bugfix in algorithm: Trigger download if the segment space is smaller than the bisection factor 

---

README.md

The locally optimistic slack requires an invite to join. Added a link on how to get an invite.

Added link on how to get a slack invite

---

README.md

Also added URL to TOML file usage.

Fixed broken "How To Use" links in README.

---

README.md

Adding a list of the databases we support to the README so people don't have to click through to the Datafold documentation for this information.

add databases we support to readme

---

.github/workflows/ci.yml
.github/workflows/ci_full.yml
pyproject.toml
tests/common.py

- Added IAM service account creds & project id in secrets
- added a sample file

[CI-149] bigquery github action

---

README.md
docs/how-to-use.md

Removed a few remaining outdated references to the pre-release.

remove references to pre-release

---

data_diff/dbt.py
tests/test_dbt.py

support combo pks in --dbt local_diff

---

data_diff/dbt_parser.py

support insecure_mode key for snowflake profile

---

data_diff/tracking.py

issue 501: instantiate dbt variables

---

data_diff/dbt_parser.py

issue 505: add client_session_keep_alive

---

README.md

Inspired by https://github.com/elementary-data/elementary/blob/master/README.md

focus readme on the dbt use case

---

README.md

center the header

---

poetry.lock
pyproject.toml

Some users are encountering the urllib3 issue [here](https://github.com/urllib3/urllib3/issues/2168)
Resolves #580

specify urllib3<2

---

data_diff/sqeleton/databases/redshift.py

fix for https://github.com/datafold/data-diff/issues/590

fix Redshift view support

---

poetry.lock
pyproject.toml

Add snowflake-connector-python support for >=3.0.0

---

poetry.lock
pyproject.toml

Resolves https://github.com/datafold/data-diff/security/dependabot/14
Note that this would raise the minimum python version to 3.7.2

snowflake-connector-python>=3.0.2

---

data_diff/dbt.py
data_diff/tracking.py
docs/usage_analytics.md

Prompts the user once on if they'd like to sign up for email notifications:
Stores if the user has already been asked in .datadiff.toml by adding a value `asked_for_email = ""`

--dbt option to sign up for email notifications

---

data_diff/__main__.py
data_diff/dbt.py

add --dbt support for --where/-w

---

data_diff/dbt_parser.py
tests/dbt_artifacts/profiles.yml
tests/test_dbt_parser.py

only render jinja in the specified profile target

---

data_diff/hashdiff_tables.py
data_diff/sqeleton/abcs/mixins.py
data_diff/sqeleton/databases/postgresql.py
data_diff/sqeleton/databases/redshift.py
data_diff/sqeleton/utils.py
docs/conf.py
tests/sqeleton/test_database.py
tests/sqeleton/test_mixins.py
tests/test_database_types.py

fixing any existing formatting issues

black -l 120 .

---

data_diff/dbt.py

Catch exceptions on "prod" table get_schema()

check prod table for DNE/access exception

---

data_diff/__main__.py
data_diff/dbt.py
tests/test_dbt.py

--columns are used as the TDiffVars.include_columns when present

add --dbt support for --columns

---

data_diff/__main__.py
data_diff/dbt.py

Add support for the `TRIGGERED_BY` env variable that overrides source of Rudderstack events

add TRIGGERED_BY env variable support

---

data_diff/dbt_parser.py
poetry.lock
pyproject.toml

support dbt 1.6

---

poetry.lock

I must have messed up a conflict merge

fix poetry.lock hash

---

poetry.lock
pyproject.toml

Make PyODBC for MS SQL optional via extras

---

data_diff/sqeleton/databases/mysql.py

Missing mediumint type in mysql
Fixing #701

[MySQL] Added mediumint

---

data_diff/cloud/datafold_api.py

`--dbt --cloud` is throwing some attribute errors after the refactor
Set frozen false
Add headers

adjust DatafoldAPI for attrs

---

data_diff/diff_tables.py
data_diff/hashdiff_tables.py
data_diff/joindiff_tables.py

Unfreeze differ classes to make it easier to extend those, including adding new attributes.

unfreeze differ classes

---

data_diff/databases/redshift.py

AbstractMixin_MD5->Mixin_MD5 to override pg version

---

README.md

Make it easy for people to interact with us live!

add vhol callout

---

data_diff/databases/databricks.py

A follow-up for 9f27117f4c98c43a61a7b4df4480f62e8d8dc909 (in #814).

Fix precision fetching for DataBricks

---

README.md

This can be run in simple scripts. Let's not confuse people to think it only runs on your local computer

remove local computer piece
